name: test_ci

on:
    push:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ex7
        run: make ex7_test

      - name: runTest
        run: make runTest

      - name: checkFormat
        run: make cFmt
